# Generated by Django 4.2.4 on 2023-10-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
