# Generated by Django 4.2.4 on 2023-10-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0002_dadossolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='entrada_usuario',
        ),
        migrations.AddField(
            model_name='historico',
            name='chuva',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historico',
            name='fosforo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historico',
            name='nitrogenio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historico',
            name='ph',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historico',
            name='potassio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historico',
            name='temperatura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historico',
            name='umidade',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='DadosSolo',
        ),
    ]
