# Generated by Django 4.2.4 on 2023-10-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0003_remove_historico_entrada_usuario_historico_chuva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='chuva',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='fosforo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='nitrogenio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='potassio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='temperatura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='umidade',
            field=models.FloatField(),
        ),
    ]
