# Generated by Django 4.2.4 on 2023-10-23 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0004_alter_historico_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='data_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
