# Generated by Django 4.2.4 on 2023-10-22 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomendacao', '0006_alter_historico_entrada_usuario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historico',
            new_name='Historico_Usuario',
        ),
    ]
