# Generated by Django 4.2.4 on 2023-10-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0008_historico_delete_historico_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
